"""fixed typo

Revision ID: 140f1a3aec01
Revises: c2b75793d83e
Create Date: 2025-02-21 15:50:50.971049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '140f1a3aec01'
down_revision = 'c2b75793d83e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('minutes_to_complete', sa.Integer(), nullable=True))
        batch_op.drop_column('minutes_to_compete')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('minutes_to_compete', sa.INTEGER(), nullable=True))
        batch_op.drop_column('minutes_to_complete')

    # ### end Alembic commands ###
